version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Print
          command: |
            ls -la
            cd ..
            mv blablanumerodeux.github.io.git me
            git clone git@github.com:blablanumerodeux/blablanumerodeux.github.io.git
            ls -la
            cd me
            hugo -d ../blablanumerodeux.github.io
