version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie

    steps:
      - checkout

      - run:
          name: Print
          command: |
            cd ..
            ls -la
            mv blablanumerodeux.github.io me
            git clone git@github.com:blablanumerodeux/blablanumerodeux.github.io.git
            ls -la
            cd me
            hugo -d ../blablanumerodeux.github.io
