version: 2
jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "48:72:5d:04:9d:79:e5:19:bc:22:43:71:c7:fa:89:3c"
      - run:
          name: Print
          command: |
            cd ..
            mv project me
            git clone git@github.com:blablanumerodeux/blablanumerodeux.github.io.git
            cd me
            git checkout hugo
            git submodule update --init --recursive
            hugo -d ../blablanumerodeux.github.io
            git config --global user.email "circleci@blablanumerodeux.com"
            git config --global user.name "CircleCi Job"
            cd ../blablanumerodeux.github.io
            git add -A
            git status
            git commit -m 'circleci commiting'
            git push


workflows:
  version: 2

  deploy:
    jobs:
      - hold:
          type: approval
      - build:
          filters:
            branches:
              only:
                - hugo

